# Generated by Django 5.1 on 2024-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/categories'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/subcategories'),
        ),
    ]
